headersOrigin = "inline"
redirectsOrigin = "inline"

[functions]

[functions."*"]

[[plugins]]
origin = "config"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "E:\\CodingProjects\\website\\.next"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

[build.environment]
NEXT_PUBLIC_SUPABASE_URL = "https://hfowyxtdtpwsndonqksu.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhmb3d5eHRkdHB3c25kb25xa3N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5MTE4NDMsImV4cCI6MjA4NjQ4Nzg0M30.jaCuwqkVO10z1m-ToRk-22Vh8s491RObJbahRY01JmE"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/_next/static/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/_next/image"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200.0
force = false

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200.0
force = false

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]